var Plugins;
(function(a){var g=function(){return function(a){"undefined"==typeof a&&(a=30);this.space=a}}(),n;a.AutosizeInputOptions=g;n=function(){function a(e,h){var f=this;this._input=$(e);this._options=$.extend({},a.getDefaultOptions(),h);this._mirror=$('<span style="position:absolute; top:-999px; left:0; white-space:pre;"/>');$.each("fontFamily fontSize fontWeight fontStyle letterSpacing textTransform wordSpacing textIndent".split(" "),function(a,e){f._mirror[0].style[e]=f._input.css(e)});$("body").append(this._mirror);this._input.on("keydown keyup input propertychange change",
function(){f.update()});f.update()}return a.prototype.getOptions=function(){return this._options},a.prototype.update=function(){var a=this._input.val()||"",h;a!==this._mirror.text()&&(this._mirror.text(a),h=this._mirror.width()+this._options.space,this._input.width(h))},a.getDefaultOptions=function(){return this._defaultOptions},a.getInstanceKey=function(){return"autosizeInputInstance"},a._defaultOptions=new g,a}();a.AutosizeInput=n;(function(g){var e="text password search url tel email number".split(" ");
g.fn.autosizeInput=function(h){return this.each(function(){if("INPUT"==this.tagName&&-1<g.inArray(this.type,e)){var f=g(this);f.data(a.AutosizeInput.getInstanceKey())||(void 0==h&&(h=f.data("autosize-input")),f.data(a.AutosizeInput.getInstanceKey(),new a.AutosizeInput(this,h)))}})};g(function(){g("input[data-autosize-input]").autosizeInput()})})(jQuery)})(Plugins||(Plugins={}));var DateFormat={};
(function(a){var g="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),n="Sun Mon Tue Wed Thu Fri Sat".split(" "),t="Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),e="January February March April May June July August September October November December".split(" "),h={Jan:"01",Feb:"02",Mar:"03",Apr:"04",May:"05",Jun:"06",Jul:"07",Aug:"08",Sep:"09",Oct:"10",Nov:"11",Dec:"12"},f=/\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.?\d{0,3}[Z\-+]?(\d{2}:?\d{2})?/;a.format=function(){function a(c){var b,
r,e,f="";-1!==c.indexOf(".")&&(b=c.split("."),c=b[0],f=b[1]);e=c.split(":");return 3===e.length?(b=e[0],r=e[1],e=e[2].replace(/\s.+/,"").replace(/[a-z]/gi,""),c=c.replace(/\s.+/,"").replace(/[a-z]/gi,""),{time:c,hour:b,minute:r,second:e,millis:f}):{time:"",hour:"",minute:"",second:"",millis:""}}function l(c,b){for(var a=b-String(c).length,e=0;e<a;e++)c="0"+c;return c}return{parseDate:function(c){var b={date:null,year:null,month:null,dayOfMonth:null,dayOfWeek:null,time:null};if("number"==typeof c)return this.parseDate(new Date(c));
if("function"==typeof c.getFullYear)b.year=String(c.getFullYear()),b.month=String(c.getMonth()+1),b.dayOfMonth=String(c.getDate()),b.time=a(c.toTimeString()+"."+c.getMilliseconds());else if(-1!=c.search(f))values=c.split(/[T\+-]/),b.year=values[0],b.month=values[1],b.dayOfMonth=values[2],b.time=a(values[3].split(".")[0]);else switch(values=c.split(" "),6===values.length&&isNaN(values[5])&&(values[values.length]="()"),values.length){case 6:b.year=values[5];c=values[1];b.month=h[c]||c;b.dayOfMonth=
values[2];b.time=a(values[3]);break;case 2:subValues=values[0].split("-");b.year=subValues[0];b.month=subValues[1];b.dayOfMonth=subValues[2];b.time=a(values[1]);break;case 7:case 9:case 10:b.year=values[3];c=values[1];b.month=h[c]||c;b.dayOfMonth=values[2];b.time=a(values[4]);break;case 1:subValues=values[0].split("");b.year=subValues[0]+subValues[1]+subValues[2]+subValues[3];b.month=subValues[5]+subValues[6];b.dayOfMonth=subValues[8]+subValues[9];b.time=a(subValues[13]+subValues[14]+subValues[15]+
subValues[16]+subValues[17]+subValues[18]+subValues[19]+subValues[20]);break;default:return null}b.date=new Date(b.year,b.month-1,b.dayOfMonth);b.dayOfWeek=String(b.date.getDay());return b},date:function(c,b){try{var a=this.parseDate(c);if(null===a)return c;for(var f=a.year,h=a.month,k=a.dayOfMonth,w=a.dayOfWeek,m=a.time,d=a="",C="",A=!1,y=0;y<b.length;y++){var z=b.charAt(y),p=b.charAt(y+1);if(A)"'"==z?(d+=""===a?"'":a,a="",A=!1):a+=z;else switch(a+=z,C="",a){case "ddd":var v=d,D,q=w;D=g[parseInt(q,
10)]||q;d=v+D;a="";break;case "dd":if("d"===p)break;d+=l(k,2);a="";break;case "d":if("d"===p)break;d+=parseInt(k,10);a="";break;case "D":k=1==k||21==k||31==k?parseInt(k,10)+"st":2==k||22==k?parseInt(k,10)+"nd":3==k||23==k?parseInt(k,10)+"rd":parseInt(k,10)+"th";d+=k;a="";break;case "MMMM":var v=d,q=h,F=parseInt(q,10)-1,d=v+(e[F]||q),a="";break;case "MMM":if("M"===p)break;var v=d,q=h,G=parseInt(q,10)-1,d=v+(t[G]||q),a="";break;case "MM":if("M"===p)break;d+=l(h,2);a="";break;case "M":if("M"===p)break;
d+=parseInt(h,10);a="";break;case "y":case "yyy":if("y"===p)break;d+=a;a="";break;case "yy":if("y"===p)break;d+=String(f).slice(-2);a="";break;case "yyyy":d+=f;a="";break;case "HH":d+=l(m.hour,2);a="";break;case "H":if("H"===p)break;d+=parseInt(m.hour,10);a="";break;case "hh":hour=0===parseInt(m.hour,10)?12:13>m.hour?m.hour:m.hour-12;d+=l(hour,2);a="";break;case "h":if("h"===p)break;hour=0===parseInt(m.hour,10)?12:13>m.hour?m.hour:m.hour-12;d+=parseInt(hour,10);a="";break;case "mm":d+=l(m.minute,
2);a="";break;case "m":if("m"===p)break;d+=m.minute;a="";break;case "ss":d+=l(m.second.substring(0,2),2);a="";break;case "s":if("s"===p)break;d+=m.second;a="";break;case "S":case "SS":if("S"===p)break;d+=a;a="";break;case "SSS":d+=m.millis.substring(0,3);a="";break;case "a":d+=12<=m.hour?"PM":"AM";a="";break;case "p":d+=12<=m.hour?"p.m.":"a.m.";a="";break;case "E":var v=d,E,q=w;E=n[parseInt(q,10)]||q;d=v+E;a="";break;case "'":a="";A=!0;break;default:d+=z,a=""}}return d+C}catch(H){return console&&
console.log&&console.log(H),c}},prettyDate:function(a){var b;if("string"===typeof a||"number"===typeof a)b=new Date(a);"object"===typeof a&&(b=new Date(a.toString()));a=((new Date).getTime()-b.getTime())/1E3;b=Math.floor(a/86400);if(!(isNaN(b)||0>b)){if(60>a)return"just now";if(120>a)return"1 minute ago";if(3600>a)return Math.floor(a/60)+" minutes ago";if(7200>a)return"1 hour ago";if(86400>a)return Math.floor(a/3600)+" hours ago";if(1===b)return"Yesterday";if(7>b)return b+" days ago";if(31>b)return Math.ceil(b/
7)+" weeks ago";if(31<=b)return"more than 5 weeks ago"}},toBrowserTimeZone:function(a,b){return this.date(new Date(a),b||"MM/dd/yyyy HH:mm:ss")}}}()})(DateFormat);(function(a){a.format=DateFormat.format})(jQuery);
(function(a){function g(e){function h(){e?l.removeData(e):u&&delete n[u]}function f(){c.id=setTimeout(function(){c.fn()},k)}var g=this,l,c={},b=e?a.fn:a,r=arguments,B=4,u=r[1],k=r[2],x=r[3];"string"!==typeof u&&(B--,u=e=0,k=r[1],x=r[2]);e?(l=g.eq(0),l.data(e,c=l.data(e)||{})):u&&(c=n[u]||(n[u]={}));c.id&&clearTimeout(c.id);delete c.id;if(x)c.fn=function(a){"string"===typeof x&&(x=b[x]);!0!==x.apply(g,t.call(r,B))||a?h():f()},f();else{if(c.fn)return void 0===k?h():c.fn(!1===k),!0;h()}}var n={},t=Array.prototype.slice;
a.doTimeout=function(){return g.apply(window,[0].concat(t.call(arguments)))};a.fn.doTimeout=function(){var a=t.call(arguments),h=g.apply(this,["doTimeout"+a[0]].concat(a));return"number"===typeof a[0]||"number"===typeof a[1]?this:h}})(jQuery);
(function(a){var g=a.fn.addClass;a.fn.addClass=function(e){for(var h=g.apply(this,arguments),f,w=0,l=this.length;w<l;w++)if(f=this[w],f instanceof SVGElement){var c=a(f).attr("class");c?-1===c.indexOf(e)&&(c=c+" "+e,a(f).attr("class",c)):a(f).attr("class",e)}return h};var n=a.fn.removeClass;a.fn.removeClass=function(e){for(var h=n.apply(this,arguments),f,g=0,l=this.length;g<l;g++)if(f=this[g],f instanceof SVGElement){var c=a(f).attr("class");if(c){var b=c.indexOf(e);-1!==b&&(c=c.substring(0,b)+c.substring(b+
e.length,c.length),a(f).attr("class",c))}}return h};var t=a.fn.hasClass;a.fn.hasClass=function(e){for(var h=t.apply(this,arguments),f,g=0,l=this.length;g<l;g++)if(f=this[g],f instanceof SVGElement)return(h=a(f).attr("class"))?-1===h.indexOf(e)?!1:!0:!1;return h}})(jQuery);
jQuery.fn.selectText=function(){var a=document,g=this[0];console.log(this,g);if(a.body.createTextRange)a=document.body.createTextRange(),a.moveToElementText(g),a.select();else if(window.getSelection){var n=window.getSelection(),a=document.createRange();a.selectNodeContents(g);n.removeAllRanges();n.addRange(a)}};